language: objective-c
matrix:
  include:
    - osx_image: xcode9.2
script:
  - xcodebuild clean test -workspace Example.xcworkspace -scheme CLMDeletionKeyHandleableTextField -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 8" | xcpretty -c
